name: 'test'

on:
  push:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: |
          npm test
  test-if-closed-pr-is-found:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - name: Build Action
        run: |
          npm run build
          npm run package
      - name: Run Action
        uses: ./
        id: pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: "fdfc72e11fcb3718f6ff37dd6ffb416096fed2ab"
      - name: Assert PR properties
        run: |
          [[ ${{ steps.pr.outputs.pr_found }} == true ]] || (echo "outputs.pr_found != true"; exit 1)
          [[ ${{ steps.pr.outputs.number }} == 2 ]] || (echo "outputs.number != 2"; exit 1)
  test-if-closed-pr-is-not-found-when-filtering-closed-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Build Action
        run: |
          npm run build
          npm run package
      - name: Run Action
        uses: ./
        id: pr
        with:
          filterOutClosed: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sha: "fdfc72e11fcb3718f6ff37dd6ffb416096fed2ab"
      - name: Exit 1, if PR was falsely found
        if: steps.pr.outputs.pr_found != 'false'
        run: echo "if 'outputs.pr_found' falsely triggered"; exit 1
      - name: Assert PR properties
        run: |
          [[ '${{ steps.pr.outputs.number }}' == '' ]] || (echo "PR falsely found"; exit 1)
